ifeq (eng,$(TARGET_BUILD_VARIANT))
VENDOR_LOG_LEVEL=I
else
VENDOR_LOG_LEVEL=S
endif

PRODUCT_VENDOR_PROPERTIES += \
    persist.log.tag.ANDR-PERF-REQUEST=$(VENDOR_LOG_LEVEL) \
    persist.log.tag.ANDR-PERF-MPCTL=$(VENDOR_LOG_LEVEL)
